### ISSUE TITLE
Configure custom pattern-comment marker

### ISSUE THREAD

**Issue by mirisuzanne** [himedlooff/doxray#22]
I'm planning to use this on an open-source project with a wide range of contributors. While `/* doxray` is a very clear regex pattern, I'm afraid it won't be immediately obvious what that is to new contributors. Any chance that could be a configuration option, or something more self-explanatory?

**Comment by himedlooff** [comment]
Closed by https://github.com/himedlooff/doxray/releases/tag/0.8.2
