### ISSUE TITLE
Expose options for extending Doxray.prototype.regex

### ISSUE THREAD

**Issue by mirisuzanne** [himedlooff/doxray#23]
The README mentions adding regex patterns as a customization, but (unlike processors) the regex block is not exposed as an option to easily pass in. Making the regex easily customizable might be a way to resolve #22, while also allowing new language additions.

**Comment by himedlooff** [comment]
Good idea! I'll add that. Sorry for the slow response. I'm just seeing these new issues. I guess I need to update my notification preferences.

**Comment by mirisuzanne** [comment]
No worries, thanks! I'm really hopeful that this approach is going to work for us - so far it's been going great. :)

**Comment by himedlooff** [comment]
This should be fixed by https://github.com/himedlooff/doxray/releases/tag/0.8.1, mind giving it a try?

**Comment by mirisuzanne** [comment]
Works great, thanks! I just copied in some of your test code, cause I liked the `@docs` marker - may just want to add documentation to the readme? You can see it set up here: https://github.com/mirisuzanne/remedocs/blob/master/src/_data/dox.js

(I'm happy for feedback on my code if you have any - I'm no JS expert)

**Comment by himedlooff** [comment]
🤦‍♂ oh yes, the README! Gotta ad it there for sure. Thanks for testing.

**Comment by himedlooff** [comment]
> Works great, thanks! I just copied in some of your test code, cause I liked the `@docs` marker - may just want to add documentation to the readme? You can see it set up here: https://github.com/mirisuzanne/remedocs/blob/master/src/_data/dox.js
> 
> (I'm happy for feedback on my code if you have any - I'm no JS expert)

JS looks good to me! I'm no expert either though 😬 
Just ran the remedocs site and that is looking legit! 🎉
